// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package onboarding

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func OnboardingView() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Buckleberry Onboarding</title><link rel=\"preconnect\" href=\"https://fonts.googleapis.com\"><link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin><script src=\"https://cdn.jsdelivr.net/npm/htmx.org@2.0.7/dist/htmx.min.js\" integrity=\"sha384-ZBXiYtYQ6hJ2Y0ZNoYuI+Nq5MqWBr+chMrS/RkXpNzQCApHEhOt2aY8EJgqwHLkJ\" crossorigin=\"anonymous\"></script><script src=\"https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js\" defer></script></head><body><h1>Welcome to Buckleberry</h1><form method=\"POST\" action=\"/onboarding\"><h2>Authentication</h2><label for=\"name\">Username</label> <input type=\"text\" name=\"username\" placeholder=\"username\" required> <label for=\"password\">Password</label> <input type=\"password\" name=\"password\" placeholder=\"password\" required><h2>Wallabag Connection</h2><label for=\"wallabag-url\">Instance URL</label> <input type=\"text\" name=\"wallabag-url\" placeholder=\"http://my-instance.wallabag.com\" required> <label for=\"wallabag-username\">Username</label> <input type=\"text\" name=\"wallabag-username\" placeholder=\"username\" required> <label for=\"wallabag-password\">Password</label> <input type=\"password\" name=\"wallabag-password\" placeholder=\"password\" required> <label for=\"wallabag-client-id\">Client ID</label> <input type=\"text\" name=\"wallbag-client-id\" placeholder=\"client id\" required> <label for=\"wallabag-client-secret\">Client Secret</label> <input type=\"password\" name=\"wallabag-client-secret\" placeholder=\"client secret\" required> <input type=\"submit\" value=\"Get Started\"></form></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
